import type { DigitalProductPassport } from "./types"

export const cushionProduct: DigitalProductPassport = {
  id: "DPP-FU-CUSH-001",
  "@type": "DigitalProductPassport",
  tenantId: "tenant-123",
  createdBy: "manufacturer-user",
  organizationId: "org-456",
  assignedUsers: ["user-1", "user-2"],

  dataClassification: "public",
  accessLevel: "standard",

  name: "EcoComfort Recycled Cushion",
  description:
    "Premium decorative cushion crafted entirely from recycled materials. Features 100% recycled cotton-polyester blend cover and recycled PET fiber fill. All materials sourced from Texcycle's circular textile facility in Varna, Bulgaria.",
  type: "CUSHION-ECO-001",
  industryType: "furniture",
  gtin: "5901234123465",
  sku: "ECO-CUSH-001",
  batchLot: "BATCH-2024-CUSH-003",
  digitalLink: "https://id.gs1.org/01/5901234123465",

  dateCreated: "2024-03-15T08:00:00Z",
  lastModification: "2024-11-19T10:30:00Z",
  createdAt: "2024-03-15T08:00:00Z",
  updatedAt: "2024-11-19T10:30:00Z",

  passportMetadata: {
    issueDate: "2024-03-15",
    expirationDate: "2029-03-15",
    status: "published",
    verified: true,
    passportId: "PASS-FU-CUSH-001",
    version: "2.0",
    registrationId: "REG-CUSH-789",
    economicOperatorId: "EO-CUSH-123",
  },

  manufacturerInfo: {
    manufacturerId: "MFR-TEXCYCLE-001",
    manufacturerName: "Texcycle Bulgaria Ltd.",
    manufacturingDate: "2024-03-10",
    manufacturerUrl: "https://texcycle.bg",
    address: {
      streetAddress: "ул. Нептун 1, Западна промишлена зона",
      city: "Varna",
      country: "Bulgaria",
      postalCode: "9023",
    },
    gln: "5901234567895",
    manufacturerContactEmail: "info@texcycle.bg",
    manufacturerContactPhone: "359 897 000 610",
  },

  materialsRegistry: [
    {
      id: "MAT-CUSH-001",
      name: "Recycled Cotton-Polyester Blend Fabric",
      category: "Textile",
      origin: "Bulgaria",
      supplier: "Texcycle Bulgaria Ltd.",
      percentage: 58,
      recycledContent: 100,
      sustainabilityInfo: {
        co2Footprint: "1.8 kg CO2e",
        waterUsage: "28 L",
        energyConsumption: "12 kWh",
        recycledContent: 100,
        recyclability: "fully_recyclable",
        certifications: ["GRS", "OEKO-TEX Standard 100", "EU Ecolabel"],
      },
      domainAttributes: {
        textile: {
          fiberType: "Cotton-Polyester Blend (60/40)",
          fiberLength: "32mm",
          strength: "High",
          elasticity: "Medium",
        },
        furniture: {
          treatment: "Pre-washed and softened",
          durability: "High",
        },
      },
      batch: "TEXCYCLE-FABRIC-2024-089",
      lot: "LOT-VN-2024-034",
      certificateRef: "GRS-TEXCYCLE-2024-089",
    },
    {
      id: "MAT-CUSH-002",
      name: "Recycled PET Fiber Fill",
      category: "Textile",
      origin: "Bulgaria",
      supplier: "Texcycle Bulgaria Ltd.",
      percentage: 37,
      recycledContent: 100,
      sustainabilityInfo: {
        co2Footprint: "1.2 kg CO2e",
        waterUsage: "18 L",
        energyConsumption: "8 kWh",
        recycledContent: 100,
        recyclability: "fully_recyclable",
        certifications: ["GRS", "Recycled Claim Standard"],
      },
      domainAttributes: {
        textile: {
          fiberType: "Recycled PET",
          fiberLength: "64mm",
          strength: "Very High",
          elasticity: "High",
        },
      },
      batch: "TEXCYCLE-FILL-2024-067",
      lot: "LOT-VN-2024-028",
      certificateRef: "GRS-TEXCYCLE-2024-067",
    },
    {
      id: "MAT-CUSH-003",
      name: "Recycled Nylon Zipper",
      category: "Hardware",
      origin: "Bulgaria",
      supplier: "Texcycle Bulgaria Ltd.",
      percentage: 5,
      recycledContent: 100,
      sustainabilityInfo: {
        co2Footprint: "0.3 kg CO2e",
        waterUsage: "5 L",
        energyConsumption: "2 kWh",
        recycledContent: 100,
        recyclability: "fully_recyclable",
        certifications: ["GRS"],
      },
      domainAttributes: {
        textile: {
          fiberType: "Recycled Nylon 6",
          strength: "Very High",
          elasticity: "Low",
        },
      },
      batch: "TEXCYCLE-ZIP-2024-045",
      lot: "LOT-VN-2024-019",
      certificateRef: "GRS-TEXCYCLE-2024-045",
    },
  ],

  productDetails: {
    color: "Ocean Blue",
    size: "50x50 cm",
    weight: 0.8,
    dimensions: {
      length: 50,
      width: 50,
      height: 15,
      unit: "cm",
    },
    materials: [
      {
        id: "MAT-CUSH-001",
        name: "Recycled Cotton-Polyester Blend Fabric",
        percentage: 58,
        origin: "Bulgaria",
        recycledContent: 100,
      },
      {
        id: "MAT-CUSH-002",
        name: "Recycled PET Fiber Fill",
        percentage: 37,
        origin: "Bulgaria",
        recycledContent: 100,
      },
      {
        id: "MAT-CUSH-003",
        name: "Recycled Nylon Zipper",
        percentage: 5,
        origin: "Bulgaria",
        recycledContent: 100,
      },
    ],
    components: [
      {
        id: "COMP-CUSH-001",
        name: "Cushion Cover",
        description: "Outer cover made from 100% recycled cotton-polyester blend",
        materials: [
          {
            id: "MAT-CUSH-001",
            name: "Recycled Cotton-Polyester Blend Fabric",
            percentage: 100,
          },
        ],
        weight: 0.35,
        recyclable: true,
        productionStepRef: "PROD-CUSH-001",
      },
      {
        id: "COMP-CUSH-002",
        name: "Inner Fill",
        description: "Cushion filling made from recycled PET bottles",
        materials: [
          {
            id: "MAT-CUSH-002",
            name: "Recycled PET Fiber Fill",
            percentage: 100,
          },
        ],
        weight: 0.4,
        recyclable: true,
        productionStepRef: "PROD-CUSH-002",
      },
      {
        id: "COMP-CUSH-003",
        name: "Closure System",
        description: "Hidden zipper closure for easy cover removal",
        materials: [
          {
            id: "MAT-CUSH-003",
            name: "Recycled Nylon Zipper",
            percentage: 100,
          },
        ],
        weight: 0.05,
        recyclable: true,
        derivedFrom: ["COMP-CUSH-001"],
        productionStepRef: "PROD-CUSH-003",
      },
    ],
    careInstructions: [
      {
        type: "cleaning",
        instruction: "Remove cover via zipper. Machine wash at 30°C with mild detergent. Air dry or tumble dry on low.",
        frequency: "Monthly or as needed",
      },
      {
        type: "maintenance",
        instruction: "Fluff cushion regularly to maintain shape. Rotate periodically for even wear.",
        frequency: "Weekly",
      },
      {
        type: "storage",
        instruction: "Store in dry, well-ventilated area. Avoid direct sunlight to prevent fading.",
        frequency: "As needed",
      },
    ],
    brandInfo: {
      brandName: "Texcycle Home",
      subBrandName: "Circular Living Collection",
      brandDescription: "100% recycled home textiles from Bulgaria's leading circular textile innovator",
      brandStory:
        "Texcycle Bulgaria was founded in 2015 in Varna with a mission to transform textile waste into beautiful, sustainable home products. Every product is made from 100% recycled materials processed in our zero-waste facility.",
      parentOrganization: "Texcycle Bulgaria Ltd.",
      brandWebsite: "https://texcycle-home.bg",
      brandCountry: "Bulgaria",
      brandEstablished: "2015",
      brandValues: ["100% Recycled", "Zero Waste", "Local Production", "Circular Economy", "Transparency"],
      socialMediaLinks: {
        website: "https://texcycle-home.bg",
        instagram: "@texcyclehome",
        facebook: "TexcycleHomeBG",
      },
    },
  },

  furnitureProperties: {
    furnitureType: "Decorative Cushion",
    style: "Contemporary Minimalist",
    dimensions: {
      length: 50,
      width: 50,
      height: 15,
    },
    weight: 0.8,
    materials: [
      {
        materialId: "MAT-CUSH-001",
        treatment: "Pre-washed and softened",
      },
    ],
    finishes: [
      {
        type: "fabric",
        color: "Ocean Blue",
        sheen: "matte",
        durability: "High resistance to pilling and fading",
        maintenanceRequirements: "Machine washable, easy care",
        vocContent: 0,
      },
    ],
    assembly: {
      assemblyRequired: false,
      estimatedTime: 0,
      toolsRequired: [],
      difficultyLevel: "easy",
      instructionsIncluded: true,
      videoGuideAvailable: false,
    },
    certifications: [
      {
        id: "CERT-CUSH-001",
        name: "GRS",
        issuingBody: "Global Recycled Standard",
        validUntil: "2026-12-31",
        certificateNumber: "GRS-TEXCYCLE-2024",
        scope: ["100% recycled content verification"],
        level: "Gold",
        issueDate: "2024-01-15",
        status: "valid",
      },
      {
        id: "CERT-CUSH-002",
        name: "OEKO-TEX Standard 100",
        issuingBody: "OEKO-TEX Association",
        validUntil: "2025-12-31",
        certificateNumber: "OEKO-TEXCYCLE-89012",
        scope: ["Textile safety and harmful substances"],
        issueDate: "2024-02-01",
        status: "valid",
      },
      {
        id: "CERT-CUSH-003",
        name: "EU Ecolabel",
        issuingBody: "European Commission",
        validUntil: "2026-06-30",
        certificateNumber: "EU-ECO-CUSH-2024",
        scope: ["Environmental performance"],
        level: "Certified",
        issueDate: "2024-03-01",
        status: "valid",
      },
    ],
    durabilityRating: 8.5,
    careInstructions: [
      {
        type: "cleaning",
        instruction: "Remove cover via zipper. Machine wash at 30°C with mild detergent. Air dry or tumble dry on low.",
        frequency: "Monthly or as needed",
        products: ["Mild Detergent", "Cold Water"],
      },
      {
        type: "maintenance",
        instruction: "Fluff cushion regularly to maintain shape. Rotate periodically for even wear.",
        frequency: "Weekly",
      },
      {
        type: "storage",
        instruction: "Store in dry, well-ventilated area. Avoid direct sunlight to prevent fading.",
        frequency: "As needed",
      },
    ],
    warranty: {
      duration: 2,
      coverage: ["Manufacturing defects", "Zipper functionality", "Fabric integrity"],
      limitations: ["Normal wear and tear", "Stains and spills", "Color fading from sun exposure"],
      claimProcess: "Contact Texcycle customer service with proof of purchase and photos.",
    },
    packaging: {
      packageCount: 1,
      totalWeight: 0.9,
      dimensions: [
        {
          length: 52,
          width: 52,
          height: 8,
          unit: "cm",
        },
      ],
      materials: ["Recycled cardboard", "Recycled paper wrap", "Compostable tape"],
      recyclable: true,
    },
  },

  sustainabilityData: {
    co2Footprint: "3.3 kg CO2e",
    carbonFootprint: "3.3 kg CO2e",
    waterUsage: "51 L",
    energyConsumption: "22 kWh",
    energySource: "renewable_solar",
    sustainabilityScore: 9.5,
    recycledContentPercentage: 100,
    recyclability: "fully_recyclable",
    repairability: "10/10 - Cover removable and replaceable",
    expectedLifespan: "8-10 years",
    chemicalsUsed: ["Water-based dyes", "Eco-friendly softeners"],
    socialCompliance: {
      fairLaborPractices: true,
      workersRights: true,
      communityImpact: "Supports local textile recycling initiatives and provides employment in Varna region",
    },
    collectionPoints: [
      {
        id: 1,
        name: "СРЕДЕЦ – ул. Калоян 54",
        address: "ул. Калоян 54, София",
        lat: 42.695430,
        lng: 23.322409,
      },
      {
        id: 2,
        name: "СРЕДЕЦ – ул. Ген. Гурко 62",
        address: "ул. Ген. Гурко 62, от страната на парка, срещу ул. Любен Каравелов, София",
        lat: 42.68939,
        lng: 23.332843,
      },
      {
        id: 3,
        name: "СРЕДЕЦ – ул. Цар Иван Асен II",
        address: "Кръстовището на ул. Цар Иван Асен II с ул. Мизия, София",
        lat: 42.689144,
        lng: 23.344159,
      },
      {
        id: 4,
        name: "КРАСНО СЕЛО – ж.к. Белите брези",
        address: "ж.к. Белите брези, ул. Лерин – срещу ДГ Брезичка, София",
        lat: 42.675249,
        lng: 23.293521,
      },
      {
        id: 5,
        name: "КРАСНО СЕЛО – ж.к. Хиподрума",
        address: "ж.к. Хиподрума, ъгъла на ул. Урвич и ул. Булаир, София",
        lat: 42.680023,
        lng: 23.296743,
      },
      {
        id: 6,
        name: "КРАСНО СЕЛО – ж.к. Борово",
        address: "ж.к. Борово, бул. Ген. Стефан Тошев, пред бл. 223, вх.А, София",
        lat: 42.671354,
        lng: 23.283280,
      },
      {
        id: 7,
        name: "КРАСНО СЕЛО – ул. Боговец",
        address: "ул. Боговец, до Районен Съд, София",
        lat: 42.685236,
        lng: 23.295664,
      },
      {
        id: 8,
        name: "КРАСНО СЕЛО – ж.к. Лагера",
        address: "ж.к. Лагера, ул. Хайдушка поляна, бл. 4 срещу Балкантон, София",
        lat: 42.683682,
        lng: 23.287439,
      },
      {
        id: 9,
        name: "КРАСНО СЕЛО – ж.к. Борово (Солун)",
        address: "ж.к. Борово, ъгъла на ул. Солун с ул. Невестина скала, пред бл. 13 А, вх. А, София",
        lat: 42.668527,
        lng: 23.286933,
      },
      {
        id: 10,
        name: "КРАСНО СЕЛО – бул. Тодор Каблешков",
        address: "бул. Тодор Каблешков, подход към пешеходен подлез, София",
        lat: 42.665868,
        lng: 23.287454,
      },
      {
        id: 11,
        name: "КРАСНО СЕЛО – ж.к. Хиподрума (ОКИ)",
        address: "ж.к. Хиподрума, ул. Булаир, алея към ОКИ Красно село, София",
        lat: 42.682437,
        lng: 23.293118,
      },
      {
        id: 12,
        name: "КРАСНО СЕЛО – ж.к. Бъкстон",
        address: "ж.к. Бъкстон, бул. Братя Бъкстон до бл. 5, София",
        lat: 42.677,
        lng: 23.29,
      },
    ],
  },

  certifications: [
    {
      id: "CERT-CUSH-001",
      name: "GRS",
      issuingBody: "Global Recycled Standard",
      validUntil: "2026-12-31",
      certificateNumber: "GRS-TEXCYCLE-2024",
      scope: ["100% recycled content verification"],
      level: "Gold",
      issueDate: "2024-01-15",
      status: "valid",
      documentUrl: "https://certificates.texcycle.bg/grs-2024",
    },
    {
      id: "CERT-CUSH-002",
      name: "OEKO-TEX Standard 100",
      issuingBody: "OEKO-TEX Association",
      validUntil: "2025-12-31",
      certificateNumber: "OEKO-TEXCYCLE-89012",
      scope: ["Textile safety and harmful substances"],
      issueDate: "2024-02-01",
      status: "valid",
      documentUrl: "https://certificates.texcycle.bg/oeko-89012",
    },
    {
      id: "CERT-CUSH-003",
      name: "EU Ecolabel",
      issuingBody: "European Commission",
      validUntil: "2026-06-30",
      certificateNumber: "EU-ECO-CUSH-2024",
      scope: ["Environmental performance"],
      level: "Certified",
      issueDate: "2024-03-01",
      status: "valid",
      documentUrl: "https://certificates.texcycle.bg/eu-eco-2024",
    },
  ],

  complianceData: {
    regulations: [
      {
        name: "REACH Regulation",
        jurisdiction: "European Union",
        status: "compliant",
        lastChecked: "2024-03-10",
      },
      {
        name: "EU Textile Regulation",
        jurisdiction: "European Union",
        status: "compliant",
        lastChecked: "2024-03-10",
      },
    ],
  },

  supplyChain: [
    {
      id: "SC-CUSH-001",
      name: "Textile Recycling Facility",
      organizationName: "Texcycle Bulgaria Ltd.",
      role: "raw_material_supplier",
      location: "Varna, Bulgaria",
      address: {
        streetAddress: "45 Recycling Boulevard",
        city: "Varna",
        country: "Bulgaria",
        postalCode: "9000",
      },
      certifications: ["GRS", "OEKO-TEX", "EU Ecolabel"],
      gln: "5901234567895",
    },
    {
      id: "SC-CUSH-002",
      name: "Manufacturing Facility",
      organizationName: "Texcycle Bulgaria Ltd.",
      role: "manufacturer",
      location: "Varna, Bulgaria",
      address: {
        streetAddress: "45 Recycling Boulevard",
        city: "Varna",
        country: "Bulgaria",
        postalCode: "9000",
      },
      certifications: ["GRS", "OEKO-TEX", "EU Ecolabel"],
      gln: "5901234567895",
    },
  ],

  productionSteps: [
    {
      id: "PROD-CUSH-001",
      stepType: "production",
      organizationName: "Texcycle Bulgaria Ltd.",
      description: "Fabric cutting and cover construction from recycled cotton-polyester blend",
      date: "2024-03-10T09:00:00Z",
      location: "Varna, Bulgaria",
      address: {
        streetAddress: "45 Recycling Boulevard",
        city: "Varna",
        country: "Bulgaria",
        postalCode: "9000",
      },
      gln: "5901234567895",
      inputRefs: ["MAT-CUSH-001"],
      outputRefs: ["COMP-CUSH-001"],
      sustainabilityData: {
        co2Total: "1.2 kg CO2e",
        waterUsageTotal: "18 L",
        energyConsumptionTotal: "8 kWh",
      },
    },
    {
      id: "PROD-CUSH-002",
      stepType: "production",
      organizationName: "Texcycle Bulgaria Ltd.",
      description: "Fill preparation from recycled PET fiber",
      date: "2024-03-10T11:00:00Z",
      location: "Varna, Bulgaria",
      address: {
        streetAddress: "45 Recycling Boulevard",
        city: "Varna",
        country: "Bulgaria",
        postalCode: "9000",
      },
      gln: "5901234567895",
      inputRefs: ["MAT-CUSH-002"],
      outputRefs: ["COMP-CUSH-002"],
      sustainabilityData: {
        co2Total: "0.8 kg CO2e",
        waterUsageTotal: "12 L",
        energyConsumptionTotal: "5 kWh",
      },
    },
    {
      id: "PROD-CUSH-003",
      stepType: "assembly",
      organizationName: "Texcycle Bulgaria Ltd.",
      description: "Zipper installation and final assembly",
      date: "2024-03-10T14:00:00Z",
      location: "Varna, Bulgaria",
      address: {
        streetAddress: "45 Recycling Boulevard",
        city: "Varna",
        country: "Bulgaria",
        postalCode: "9000",
      },
      gln: "5901234567895",
      inputRefs: ["COMP-CUSH-001", "COMP-CUSH-002", "MAT-CUSH-003"],
      outputRefs: ["COMP-CUSH-003", "DPP-FU-CUSH-001"],
      sustainabilityData: {
        co2Total: "0.8 kg CO2e",
        waterUsageTotal: "15 L",
        energyConsumptionTotal: "6 kWh",
      },
    },
    {
      id: "PROD-CUSH-004",
      stepType: "quality_check",
      organizationName: "Texcycle Bulgaria Ltd.",
      description: "Quality inspection and certification verification",
      date: "2024-03-10T16:00:00Z",
      location: "Varna, Bulgaria",
      address: {
        streetAddress: "45 Recycling Boulevard",
        city: "Varna",
        country: "Bulgaria",
        postalCode: "9000",
      },
      gln: "5901234567895",
      inputRefs: ["DPP-FU-CUSH-001"],
      sustainabilityData: {
        co2Total: "0.5 kg CO2e",
        waterUsageTotal: "6 L",
        energyConsumptionTotal: "3 kWh",
      },
    },
  ],

  services: [
    {
      name: "Cover Replacement Service",
      serviceType: "repair",
      description: "Replace worn covers with new recycled fabric covers",
    },
    {
      name: "Fill Refresh Service",
      serviceType: "refurbishment",
      description: "Refresh cushion fill to restore original comfort",
    },
    {
      name: "Textile Recycling Return",
      serviceType: "recycling",
      description: "Return program for end-of-life cushions - 100% recycled into new products",
    },
    {
      name: "Professional Cleaning",
      serviceType: "maintenance",
      description: "Expert cleaning service for delicate recycled textiles",
    },
  ],

  images: {
    productImages: [
      {
        id: "IMG-CUSH-001",
        url: "/ocean-blue-decorative-cushion-recycled-fabric-fron.jpg",
        alt: "EcoComfort Recycled Cushion - Front View",
        caption: "Ocean blue cushion made from 100% recycled materials",
        isPrimary: true,
      },
      
      {
        id: "IMG-CUSH-003",
        url: "/cushion-zipper-detail-recycled-nylon-close-up.jpg",
        alt: "EcoComfort Recycled Cushion - Zipper Detail",
        caption: "Hidden recycled nylon zipper for easy cover removal",
        isPrimary: false,
      },
    ],
  },

  visibility: {
    isPublic: true,
    allowedRoles: ["consumer", "retailer"],
  },

  version: "2.0",
}
