import type { DigitalProductPassport } from "./types"

export const sofaProduct: DigitalProductPassport = {
  id: "DPP-FU-SOFA-001",
  "@type": "DigitalProductPassport",
  tenantId: "tenant-123",
  createdBy: "manufacturer-user",
  organizationId: "org-456",
  assignedUsers: ["user-1", "user-2"],

  dataClassification: "public",
  accessLevel: "standard",

  name: "EcoSofa Comfort Plus",
  description:
    "A luxurious 3-seater sofa crafted with sustainability in mind. Features 100% recycled textiles and eco-friendly cushion fill made from recycled plastic bottles. Perfect for modern living spaces with a commitment to the environment.",
  type: "SOFA-ECO-001",
  industryType: "furniture",
  gtin: "5901234123458",
  sku: "ECO-SOFA-001",
  batchLot: "BATCH-2024-002",
  digitalLink: "https://id.gs1.org/01/5901234123458",

  dateCreated: "2024-02-10T08:00:00Z",
  lastModification: "2024-11-12T14:30:00Z",
  createdAt: "2024-02-10T08:00:00Z",
  updatedAt: "2024-11-12T14:30:00Z",

  passportMetadata: {
    issueDate: "2024-02-10",
    expirationDate: "2029-02-10",
    status: "published",
    verified: true,
    passportId: "PASS-FU-SOFA-001",
    version: "2.0",
    registrationId: "REG-789456",
    economicOperatorId: "EO-789",
  },

  manufacturerInfo: {
    manufacturerId: "MFR-001",
    manufacturerName: "EcoWood Furniture Co.",
    manufacturingDate: "2024-02-05",
    manufacturerUrl: "https://ecowood-furniture.example",
    address: {
      streetAddress: "123 Timber Lane",
      city: "Sofia",
      country: "Bulgaria",
      postalCode: "1000",
    },
    gln: "5901234567890",
    manufacturerContactEmail: "contact@ecowood.example",
    manufacturerContactPhone: "+359 2 123 4567",
  },

  materialsRegistry: [
    {
      id: "MAT-SOFA-001",
      name: "Recycled Polyester Fabric",
      category: "Textile",
      origin: "Netherlands",
      supplier: "GreenFiber Textiles B.V.",
      percentage: 45,
      recycledContent: 100,
      sustainabilityInfo: {
        co2Footprint: "3.2 kg CO2e",
        waterUsage: "45 L",
        energyConsumption: "18 kWh",
        recycledContent: 100,
        recyclability: "fully_recyclable",
        certifications: ["GRS", "OEKO-TEX Standard 100", "GOTS"],
      },
      domainAttributes: {
        textile: {
          fiberType: "Polyester",
          fiberLength: "38mm",
          strength: "High",
          elasticity: "Medium",
        },
      },
      batch: "POLY-2024-078",
      certificateRef: "GRS-2024-001",
    },
    {
      id: "MAT-SOFA-002",
      name: "Recycled PET Cushion Fill",
      category: "Textile",
      origin: "Germany",
      supplier: "RecycleFill GmbH",
      percentage: 30,
      recycledContent: 95,
      sustainabilityInfo: {
        co2Footprint: "2.8 kg CO2e",
        waterUsage: "32 L",
        energyConsumption: "14 kWh",
        recycledContent: 95,
        recyclability: "fully_recyclable",
        certifications: ["GRS", "Cradle to Cradle"],
      },
      domainAttributes: {
        textile: {
          fiberType: "PET Fiber",
          fiberLength: "64mm",
          strength: "Very High",
          elasticity: "High",
        },
      },
      batch: "PET-2024-045",
      certificateRef: "GRS-2024-002",
    },
    {
      id: "MAT-SOFA-003",
      name: "FSC Birch Plywood Frame",
      category: "Wood",
      origin: "Finland",
      supplier: "Nordic Wood Suppliers Oy",
      percentage: 18,
      recycledContent: 0,
      sustainabilityInfo: {
        co2Footprint: "6.4 kg CO2e",
        waterUsage: "85 L",
        energyConsumption: "32 kWh",
        recycledContent: 0,
        recyclability: "fully_recyclable",
        certifications: ["FSC", "PEFC"],
      },
      domainAttributes: {
        furniture: {
          species: "Birch",
          grade: "Grade A",
          treatment: "Natural Finish",
          durability: "Very High",
        },
      },
      batch: "BIRCH-2024-023",
      certificateRef: "FSC-C789456",
    },
    {
      id: "MAT-SOFA-004",
      name: "Recycled Steel Springs",
      category: "Metal",
      origin: "Sweden",
      supplier: "Nordic Steel AB",
      percentage: 7,
      recycledContent: 85,
      sustainabilityInfo: {
        co2Footprint: "2.1 kg CO2e",
        waterUsage: "18 L",
        energyConsumption: "12 kWh",
        recycledContent: 85,
        recyclability: "fully_recyclable",
        certifications: ["ISO 14001"],
      },
      batch: "STEEL-2024-056",
    },
  ],

  productDetails: {
    color: "Sage Green",
    size: "3-Seater",
    weight: 65,
    dimensions: {
      length: 210,
      width: 90,
      height: 85,
      unit: "cm",
    },
    materials: [
      {
        id: "MAT-SOFA-001",
        name: "Recycled Polyester Fabric",
        percentage: 45,
        origin: "Netherlands",
        recycledContent: 100,
      },
      {
        id: "MAT-SOFA-002",
        name: "Recycled PET Cushion Fill",
        percentage: 30,
        origin: "Germany",
        recycledContent: 95,
      },
      {
        id: "MAT-SOFA-003",
        name: "FSC Birch Plywood Frame",
        percentage: 18,
        origin: "Finland",
        recycledContent: 0,
      },
      {
        id: "MAT-SOFA-004",
        name: "Recycled Steel Springs",
        percentage: 7,
        origin: "Sweden",
        recycledContent: 85,
      },
    ],
    components: [
      {
        id: "COMP-SOFA-001",
        name: "Sofa Frame",
        description: "Main structural frame made from FSC-certified birch plywood",
        materials: [
          {
            id: "MAT-SOFA-003",
            name: "FSC Birch Plywood Frame",
            percentage: 100,
          },
        ],
        weight: 25,
        recyclable: true,
      },
      {
        id: "COMP-SOFA-002",
        name: "Seat Cushions (3x)",
        description: "Three seat cushions filled with recycled PET fiber",
        materials: [
          {
            id: "MAT-SOFA-001",
            name: "Recycled Polyester Fabric",
            percentage: 40,
          },
          {
            id: "MAT-SOFA-002",
            name: "Recycled PET Cushion Fill",
            percentage: 60,
          },
        ],
        weight: 18,
        recyclable: true,
      },
      {
        id: "COMP-SOFA-003",
        name: "Back Cushions (3x)",
        description: "Three back cushions with recycled polyester cover and PET fill",
        materials: [
          {
            id: "MAT-SOFA-001",
            name: "Recycled Polyester Fabric",
            percentage: 35,
          },
          {
            id: "MAT-SOFA-002",
            name: "Recycled PET Cushion Fill",
            percentage: 65,
          },
        ],
        weight: 12,
        recyclable: true,
      },
      {
        id: "COMP-SOFA-004",
        name: "Spring System",
        description: "Zigzag spring system made from recycled steel",
        materials: [
          {
            id: "MAT-SOFA-004",
            name: "Recycled Steel Springs",
            percentage: 100,
          },
        ],
        weight: 8,
        recyclable: true,
      },
      {
        id: "COMP-SOFA-005",
        name: "Upholstery",
        description: "100% recycled polyester fabric covering",
        materials: [
          {
            id: "MAT-SOFA-001",
            name: "Recycled Polyester Fabric",
            percentage: 100,
          },
        ],
        weight: 2,
        recyclable: true,
      },
    ],
    careInstructions: [
      {
        type: "cleaning",
        instruction: "Vacuum regularly with upholstery attachment. Spot clean with mild detergent and water.",
        frequency: "Weekly",
      },
      {
        type: "maintenance",
        instruction: "Rotate cushions every 2-3 months for even wear. Check and tighten frame bolts annually.",
        frequency: "Quarterly",
      },
    ],
    brandInfo: {
      brandName: "EcoWood Premium",
      subBrandName: "Comfort Collection",
      brandDescription: "Sustainably crafted furniture for modern living",
      brandStory:
        "Founded in 2010, EcoWood Premium is committed to sustainable furniture manufacturing using recycled and responsibly sourced materials.",
      parentOrganization: "EcoWood Furniture Co.",
      brandWebsite: "https://ecowood-premium.example",
      brandCountry: "Bulgaria",
      brandEstablished: "2010",
      brandValues: ["Sustainability", "Quality", "Innovation", "Circular Economy"],
    },
  },

  furnitureProperties: {
    furnitureType: "Sofa",
    style: "Contemporary Minimalist",
    dimensions: {
      length: 210,
      width: 90,
      height: 85,
      seatHeight: 42,
      depth: 90,
    },
    weight: 65,
    materials: [
      {
        materialId: "MAT-SOFA-003",
        species: "Birch",
        grade: "Grade A",
        treatment: "Natural Finish",
      },
    ],
    finishes: [
      {
        type: "fabric",
        color: "Sage Green",
        sheen: "matte",
        durability: "High resistance to wear and pilling",
        maintenanceRequirements: "Vacuum regularly, professional cleaning annually",
        vocContent: 0,
      },
    ],
    assembly: {
      assemblyRequired: true,
      estimatedTime: 45,
      toolsRequired: ["Allen key (included)", "Screwdriver"],
      difficultyLevel: "medium",
      instructionsIncluded: true,
      videoGuideAvailable: true,
    },
    certifications: [
      {
        id: "CERT-SOFA-001",
        name: "GRS",
        issuingBody: "Global Recycled Standard",
        validUntil: "2026-12-31",
        certificateNumber: "GRS-2024-001",
        scope: ["Recycled content verification"],
        level: "Gold",
        issueDate: "2024-01-01",
        status: "valid",
      },
      {
        id: "CERT-SOFA-002",
        name: "OEKO-TEX Standard 100",
        issuingBody: "OEKO-TEX Association",
        validUntil: "2025-12-31",
        certificateNumber: "OEKO-78902",
        scope: ["Textile safety"],
        issueDate: "2024-01-01",
        status: "valid",
      },
      {
        id: "CERT-SOFA-003",
        name: "FSC",
        issuingBody: "Forest Stewardship Council",
        validUntil: "2026-12-31",
        certificateNumber: "FSC-C789456",
        scope: ["Wood sourcing"],
        level: "Gold",
        issueDate: "2024-01-01",
        status: "valid",
      },
    ],
    durabilityRating: 9,
    loadCapacity: 300,
    fireResistance: {
      standard: "BS 5852",
      rating: "High",
      testDate: "2024-02-01",
    },
    formaldehyde: {
      level: "E0",
      testMethod: "EN 717-1",
      value: 0.02,
      testDate: "2024-02-01",
    },
    careInstructions: [
      {
        type: "cleaning",
        instruction: "Vacuum regularly with upholstery attachment. Spot clean with mild detergent and water.",
        frequency: "Weekly",
        products: ["Mild Detergent", "Soft Brush"],
      },
      {
        type: "maintenance",
        instruction: "Rotate cushions every 2-3 months for even wear. Check and tighten frame bolts annually.",
        frequency: "Quarterly",
      },
      {
        type: "storage",
        instruction: "If storing, keep in dry place with breathable cover. Avoid plastic wrapping.",
        frequency: "As needed",
      },
    ],
    warranty: {
      duration: 7,
      coverage: ["Manufacturing defects", "Structural integrity", "Frame warranty"],
      limitations: ["Normal wear and tear", "Damage from misuse", "Stains and spills"],
      claimProcess: "Contact customer service with proof of purchase and photos of defect.",
    },
    packaging: {
      packageCount: 2,
      totalWeight: 75,
      dimensions: [
        {
          length: 215,
          width: 95,
          height: 45,
          unit: "cm",
        },
        {
          length: 95,
          width: 85,
          height: 35,
          unit: "cm",
        },
      ],
      materials: ["Recycled cardboard", "Biodegradable wrap", "Recycled paper padding"],
      recyclable: true,
    },
  },

  sustainabilityData: {
    co2Footprint: "14.5 kg CO2e",
    carbonFootprint: "14.5 kg CO2e",
    waterUsage: "180 L",
    energyConsumption: "76 kWh",
    energySource: "renewable_mix",
    sustainabilityScore: 9.2,
    recycledContentPercentage: 75,
    recyclability: "fully_recyclable",
    repairability: "9/10 - Easy to repair and replace components",
    expectedLifespan: "20-25 years",
    chemicalsUsed: ["Water-based adhesive", "Low-VOC finishing"],
    socialCompliance: {
      fairLaborPractices: true,
      workersRights: true,
      communityImpact: "Supports local recycling communities and circular economy initiatives",
    },
  },

  certifications: [
    {
      id: "CERT-SOFA-001",
      name: "GRS",
      issuingBody: "Global Recycled Standard",
      validUntil: "2026-12-31",
      certificateNumber: "GRS-2024-001",
      scope: ["Recycled content verification"],
      level: "Gold",
      issueDate: "2024-01-01",
      status: "valid",
      documentUrl: "https://certificates.example/grs-2024-001",
    },
    {
      id: "CERT-SOFA-002",
      name: "OEKO-TEX Standard 100",
      issuingBody: "OEKO-TEX Association",
      validUntil: "2025-12-31",
      certificateNumber: "OEKO-78902",
      scope: ["Textile safety"],
      issueDate: "2024-01-01",
      status: "valid",
      documentUrl: "https://certificates.example/oeko-78902",
    },
    {
      id: "CERT-SOFA-003",
      name: "FSC",
      issuingBody: "Forest Stewardship Council",
      validUntil: "2026-12-31",
      certificateNumber: "FSC-C789456",
      scope: ["Wood sourcing"],
      level: "Gold",
      issueDate: "2024-01-01",
      status: "valid",
      documentUrl: "https://certificates.example/fsc-c789456",
    },
    {
      id: "CERT-SOFA-004",
      name: "Cradle to Cradle",
      issuingBody: "Cradle to Cradle Products Innovation Institute",
      validUntil: "2026-06-30",
      certificateNumber: "C2C-2024-SOFA",
      scope: ["Circular design"],
      level: "Silver",
      issueDate: "2024-01-15",
      status: "valid",
      documentUrl: "https://certificates.example/c2c-2024-sofa",
    },
  ],

  complianceData: {
    regulations: [
      {
        name: "EU Timber Regulation",
        jurisdiction: "European Union",
        status: "compliant",
        lastChecked: "2024-02-05",
      },
      {
        name: "REACH Regulation",
        jurisdiction: "European Union",
        status: "compliant",
        lastChecked: "2024-02-05",
      },
    ],
  },

  supplyChain: [
    {
      id: "SC-SOFA-001",
      name: "Textile Recycler",
      organizationName: "GreenFiber Textiles B.V.",
      role: "raw_material_supplier",
      location: "Amsterdam, Netherlands",
      address: {
        city: "Amsterdam",
        country: "Netherlands",
      },
      certifications: ["GRS", "OEKO-TEX", "GOTS"],
      gln: "5901234567892",
    },
    {
      id: "SC-SOFA-002",
      name: "Fill Material Supplier",
      organizationName: "RecycleFill GmbH",
      role: "raw_material_supplier",
      location: "Munich, Germany",
      address: {
        city: "Munich",
        country: "Germany",
      },
      certifications: ["GRS", "Cradle to Cradle"],
      gln: "5901234567893",
    },
    {
      id: "SC-SOFA-003",
      name: "Wood Supplier",
      organizationName: "Nordic Wood Suppliers Oy",
      role: "raw_material_supplier",
      location: "Helsinki, Finland",
      address: {
        city: "Helsinki",
        country: "Finland",
      },
      certifications: ["FSC", "PEFC"],
      gln: "5901234567894",
    },
    {
      id: "SC-SOFA-004",
      name: "Manufacturing Plant",
      organizationName: "EcoWood Furniture Co.",
      role: "manufacturer",
      location: "Sofia, Bulgaria",
      address: {
        streetAddress: "123 Timber Lane",
        city: "Sofia",
        country: "Bulgaria",
        postalCode: "1000",
      },
      gln: "5901234567890",
    },
  ],

  productionSteps: [
    {
      id: "PROD-SOFA-001",
      stepType: "production",
      organizationName: "EcoWood Furniture Co.",
      description: "Frame construction from FSC birch plywood",
      date: "2024-02-05T09:00:00Z",
      location: "Sofia, Bulgaria",
      inputRefs: ["MAT-SOFA-003"],
      outputRefs: ["COMP-SOFA-001"],
      sustainabilityData: {
        co2Total: "4.2 kg CO2e",
        waterUsageTotal: "55 L",
        energyConsumptionTotal: "28 kWh",
      },
    },
    {
      id: "PROD-SOFA-002",
      stepType: "production",
      organizationName: "EcoWood Furniture Co.",
      description: "Spring system installation",
      date: "2024-02-06T10:00:00Z",
      location: "Sofia, Bulgaria",
      inputRefs: ["MAT-SOFA-004", "COMP-SOFA-001"],
      outputRefs: ["COMP-SOFA-004"],
      sustainabilityData: {
        co2Total: "1.8 kg CO2e",
        waterUsageTotal: "15 L",
        energyConsumptionTotal: "10 kWh",
      },
    },
    {
      id: "PROD-SOFA-003",
      stepType: "production",
      organizationName: "EcoWood Furniture Co.",
      description: "Cushion manufacturing with recycled fill",
      date: "2024-02-06T14:00:00Z",
      location: "Sofia, Bulgaria",
      inputRefs: ["MAT-SOFA-001", "MAT-SOFA-002"],
      outputRefs: ["COMP-SOFA-002", "COMP-SOFA-003"],
      sustainabilityData: {
        co2Total: "3.5 kg CO2e",
        waterUsageTotal: "48 L",
        energyConsumptionTotal: "20 kWh",
      },
    },
    {
      id: "PROD-SOFA-004",
      stepType: "assembly",
      organizationName: "EcoWood Furniture Co.",
      description: "Final upholstery and assembly",
      date: "2024-02-07T09:00:00Z",
      location: "Sofia, Bulgaria",
      inputRefs: ["COMP-SOFA-001", "COMP-SOFA-002", "COMP-SOFA-003", "COMP-SOFA-004", "MAT-SOFA-001"],
      outputRefs: ["DPP-FU-SOFA-001"],
      sustainabilityData: {
        co2Total: "5.0 kg CO2e",
        waterUsageTotal: "62 L",
        energyConsumptionTotal: "18 kWh",
      },
    },
    {
      id: "PROD-SOFA-005",
      stepType: "quality_check",
      organizationName: "EcoWood Furniture Co.",
      description: "Quality inspection and certification",
      date: "2024-02-07T15:00:00Z",
      location: "Sofia, Bulgaria",
      inputRefs: ["DPP-FU-SOFA-001"],
      sustainabilityData: {
        co2Total: "0 kg CO2e",
        waterUsageTotal: "0 L",
        energyConsumptionTotal: "0 kWh",
      },
    },
  ],

  services: [
    {
      name: "Professional Upholstery Cleaning",
      serviceType: "maintenance",
      description: "Expert furniture cleaning service for recycled textiles",
    },
    {
      name: "Component Replacement",
      serviceType: "repair",
      description: "Replace cushions, springs, or frame components",
    },
    {
      name: "Textile Recycling Program",
      serviceType: "recycling",
      description: "Return program for end-of-life recycling of all components",
    },
    {
      name: "Cushion Refill Service",
      serviceType: "refurbishment",
      description: "Refresh cushions with new recycled fill",
    },
  ],

  images: {
    productImages: [
      {
        id: "IMG-SOFA-001",
        url: "/sage-green-modern-sofa-with-cushions-front-view.jpg",
        alt: "EcoSofa Comfort Plus - Front View",
        caption: "Front view showcasing sage green recycled polyester fabric",
        isPrimary: true,
      },
      {
        id: "IMG-SOFA-002",
        url: "/modern-sofa-side-view-with-cushions.jpg",
        alt: "EcoSofa Comfort Plus - Side View",
        caption: "Side profile highlighting comfort and design",
        isPrimary: false,
      },
      {
        id: "IMG-SOFA-003",
        url: "/sofa-cushion-detail-textile-close-up.jpg",
        alt: "EcoSofa Comfort Plus - Fabric Detail",
        caption: "Close-up of recycled polyester textile",
        isPrimary: false,
      },
    ],
  },

  visibility: {
    isPublic: true,
    allowedRoles: ["consumer", "retailer"],
  },

  version: "2.0",
}
